### ISSUE TITLE
0.1.4 does not appear to be on master branch(?)

### ISSUE THREAD

**Issue by t-vi** [GregBowyer/cld2-cffi#13]
Hello Greg,

thank you for cld2-cffi.
When building from the git repo, I noticed that the master branch still seems to be saying "0.1.3" as version, it appears that the final 0.1.4 commit is missing.
I have not really been able to find a branch with the 0.1.4 commit. Would it be possible to add that to the master branch.

Best regards

Thomas

**Comment by rmax** [comment]
There is the tag 0.1.4 with a commit but it doesn't appear on master, odd. Check here https://github.com/GregBowyer/cld2-cffi/commits/0.1.4

**Comment by GregBowyer** [comment]
Thanks for the spot, fixed
