### ISSUE TITLE
Issue with release 0.1.2 ?

### ISSUE THREAD

**Issue by taynaud** [GregBowyer/cld2-cffi#6]
Hello,

There is a disrepencie between
https://pypi.python.org/pypi/cld2-cffi
and
https://pypi.python.org/simple/cld2-cffi/

The second one does not contain the 0.1.2 version. Is it a release issue ?

Best,

**Comment by gryBox** [comment]
A related issue - Using `pip install cld2-cffi` returns 0.1.1 install, (which fails on my Win 7 64 python 3.5). Trying to use pip install cld2-cffi==0.1.2 also fails for other reasons.  Any suggestions on how to download 0.1.2

**Comment by GregBowyer** [comment]
Sorry only just saw this, not sure I might do a new release. I also don't know how this installs on windows as windows typically does not include a build environment.

**Comment by pquentin** [comment]
A new release would be nice, but I don't think that prevents making sure the archive is uploaded to PyPI. (Our workaround was to do this ourselves in our private devpi instance.)

**Comment by GregBowyer** [comment]
Does 0.1.3 solve issues for you?

**Comment by gryBox** [comment]
Thank you ... I will try it out this weekend and let you know

Itay Livni

**Comment by gryBox** [comment]
@GregBowyer Unfortunately not. Does it have to do with the c compiler in my Windows 7 installation ?

![cld2_bug](https://cloud.githubusercontent.com/assets/16763201/17460587/c1873d5c-5c33-11e6-880b-5615d6772bc2.PNG)

**Comment by GregBowyer** [comment]
Ah try from github directly rather than from release

On Sat, Aug 6, 2016, at 10:13 PM, gryBox wrote:

> @GregBowyer[1] Unfortunately not. Does it have to do with the c
> compiler in my Windows 7 installation ?
> cld2_bug
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:
1. https://github.com/GregBowyer
2. https://github.com/GregBowyer/cld2-cffi/issues/6#issuecomment-238064149

**Comment by gryBox** [comment]
@GregBowyer The version on Github worked! :+1:    

Thank you..

**Comment by taynaud** [comment]
It fixes the issue, thanks !
